version: '3.8'

services:
  client:
    build: ./Client
    ports:
      - "5173:5173"
    networks:
      - app-network

  server:
    build: ./Server
    container_name: ecommerce_server
    environment:
      SPRING_APPLICATION_NAME: SpringEcom
      DB_URL: jdbc:postgresql://db:5432/mydb
      DB_USER: postgres
      DB_PASS: 12345
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ecommerce_nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

